--- 
abstract: Glue of modules for fighting with Japanese mobile web
author: 
  - Naoki Tomita <tomita@cpan.org>
build_requires: 
  HTTP::MobileAgent: 0
  Test::Base: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-MobileJp-Filter
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::MOP: 0
  Class::Trigger: 0
  Encode: 2.25
  Encode::JP::Mobile: 0.25
  Encode::JP::Mobile::Charnames: 0
  HTML::DoCoMoCSS: 0
  HTML::Entities::ConvertPictogramMobileJp: 0
  HTML::StickyQuery::DoCoMoGUID: 0
  Moose: 0.55
  Moose::Role: 0
  YAML: 0
version: 0.01_02
