--- 
abstract: Glue modules for fighting Japanese mobile web
author: 
  - Naoki Tomita <tomita@cpan.org>
build_requires: 
  Test::Base: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-MobileJp-Filter
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Trigger: 0
  Encode: 0
  Encode::JP::Mobile: 0
  HTML::DoCoMoCSS: 0
  HTML::Entities::ConvertPictogramMobileJp: 0
  HTML::StickyQuery::DoCoMoGUID: 0
  HTTP::MobileAgent: 0
  UNIVERSAL::require: 0
version: 0.01
